import { CASHBACK_LEG_CHIP, cashbackOrderDetailRows } from './cashbackOrderDetailRows'
import { LOYALTY_LIST_BOOSTER_BADGE, loyaltyOrderDetailRows } from './loyaltyOrderDetailRows'
import { cashbackPackDetailRows, loyaltyPackDetailRows } from './packDetailRows'
import type { PackConfig, PackVariantKey } from './types'

export const PACK_CONFIG: Record<PackVariantKey, PackConfig> = {
  'loyalty-upcoming': {
    navTitle: 'Loyalty rewards',
    chip: { text: 'Upcoming', tone: 'warning' },
    heroIcon: 'crown',
    amount: '+45.78 EXD',
    details: loyaltyPackDetailRows('Available on', 'Jan 31, 2026, 18:43 UTC', '21 Jan 2026 – 25 Jan 2026'),
    orders: [
      {
        id: 'ly-u-1',
        listIcon: 'crown',
        title: 'Loyalty reward',
        listBoosterBadge: LOYALTY_LIST_BOOSTER_BADGE,
        amount: '+15.27 EXD',
        meta: ['Account: #12345678', 'Order: 8829103'],
        date: 'Jan 25, 16:06',
        detail: {
          navTitle: 'Loyalty reward',
          chip: { text: 'Upcoming', tone: 'warning' },
          heroIcon: 'crown',
          amount: '+15.27 EXD',
          details: loyaltyOrderDetailRows('upcoming', 'Jan 25, 2026, 16:06 UTC', '8829103'),
        },
      },
      {
        id: 'ly-u-2',
        listIcon: 'crown',
        title: 'Loyalty reward',
        listBoosterBadge: LOYALTY_LIST_BOOSTER_BADGE,
        amount: '+15.26 EXD',
        meta: ['Account: #12345678', 'Order: 8829104'],
        date: 'Jan 25, 16:06',
        detail: {
          navTitle: 'Loyalty reward',
          chip: { text: 'Upcoming', tone: 'warning' },
          heroIcon: 'crown',
          amount: '+15.26 EXD',
          details: loyaltyOrderDetailRows('upcoming', 'Jan 25, 2026, 16:06 UTC', '8829104'),
        },
      },
      {
        id: 'ly-u-3',
        listIcon: 'crown',
        title: 'Loyalty reward',
        listBoosterBadge: LOYALTY_LIST_BOOSTER_BADGE,
        amount: '+15.25 EXD',
        meta: ['Account: #12345678', 'Order: 8829105'],
        date: 'Jan 25, 16:06',
        detail: {
          navTitle: 'Loyalty reward',
          chip: { text: 'Upcoming', tone: 'warning' },
          heroIcon: 'crown',
          amount: '+15.25 EXD',
          details: loyaltyOrderDetailRows('upcoming', 'Jan 25, 2026, 16:06 UTC', '8829105'),
        },
      },
    ],
  },
  'loyalty-activated': {
    navTitle: 'Loyalty rewards',
    chip: { text: 'Activated', tone: 'success' },
    heroIcon: 'crown',
    amount: '+89.23 EXD',
    details: loyaltyPackDetailRows('Activated on', 'Jan 15, 2026, 16:15 UTC', 'Mar 9–15'),
    orders: [
      {
        id: 'ly-a-1',
        listIcon: 'crown',
        title: 'Loyalty reward',
        listBoosterBadge: LOYALTY_LIST_BOOSTER_BADGE,
        amount: '+44.62 EXD',
        meta: ['Account: #12345678', 'Order: 8812001'],
        date: '10 Jan',
        detail: {
          navTitle: 'Loyalty reward',
          chip: { text: 'Activated', tone: 'success' },
          heroIcon: 'crown',
          amount: '+44.62 EXD',
          details: loyaltyOrderDetailRows('activated', 'Jan 15, 2026, 16:15 UTC', '8812001'),
        },
      },
      {
        id: 'ly-a-2',
        listIcon: 'crown',
        title: 'Loyalty reward',
        listBoosterBadge: LOYALTY_LIST_BOOSTER_BADGE,
        amount: '+44.61 EXD',
        meta: ['Account: #12345678', 'Order: 8812002'],
        date: '10 Jan',
        detail: {
          navTitle: 'Loyalty reward',
          chip: { text: 'Activated', tone: 'success' },
          heroIcon: 'crown',
          amount: '+44.61 EXD',
          details: loyaltyOrderDetailRows('activated', 'Jan 15, 2026, 16:15 UTC', '8812002'),
        },
      },
    ],
  },
  'cashback-upcoming': {
    navTitle: 'EXD cashback',
    chip: { text: 'Upcoming', tone: 'warning' },
    heroIcon: 'dollar',
    amount: '+3.70 USD',
    details: cashbackPackDetailRows('Credits on', 'Jan 14, 2026, 08:00 UTC', 'Mar 22'),
    orders: [
      {
        id: 'cb-u-1',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 12345682'],
        date: 'Jan 15, 16:06',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: CASHBACK_LEG_CHIP,
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: cashbackOrderDetailRows('Mar 22', '12345682', 'Mar 22, 2026, 16:06 UTC'),
        },
      },
      {
        id: 'cb-u-2',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 12345683'],
        date: 'Jan 15, 16:06',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: CASHBACK_LEG_CHIP,
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: cashbackOrderDetailRows('Mar 22', '12345683', 'Mar 22, 2026, 16:06 UTC'),
        },
      },
      {
        id: 'cb-u-3',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 12345684'],
        date: 'Jan 15, 16:06',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: CASHBACK_LEG_CHIP,
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: cashbackOrderDetailRows('Mar 22', '12345684', 'Mar 22, 2026, 16:06 UTC'),
        },
      },
    ],
  },
  'cashback-activated': {
    navTitle: 'EXD cashback',
    chip: { text: 'Credited', tone: 'success' },
    heroIcon: 'dollar',
    amount: '+3.70 USD',
    details: cashbackPackDetailRows(
      'Credited on',
      'Jan 14, 2026, 16:06 UTC',
      'Jan 13',
      '#12345678',
    ),
    orders: [
      {
        id: 'cb-a-1',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 9130201'],
        date: '14 Jan',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: CASHBACK_LEG_CHIP,
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: cashbackOrderDetailRows('Jan 13', '9130201', 'Jan 13, 2026, 16:06 UTC'),
        },
      },
      {
        id: 'cb-a-2',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 9130202'],
        date: '14 Jan',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: CASHBACK_LEG_CHIP,
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: cashbackOrderDetailRows('Jan 13', '9130202', 'Jan 13, 2026, 16:06 UTC'),
        },
      },
      {
        id: 'cb-a-3',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 9130203'],
        date: '14 Jan',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: CASHBACK_LEG_CHIP,
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: cashbackOrderDetailRows('Jan 13', '9130203', 'Jan 13, 2026, 16:06 UTC'),
        },
      },
    ],
  },
  'cashback-activated-jan12': {
    navTitle: 'EXD cashback',
    chip: { text: 'Credited', tone: 'success' },
    heroIcon: 'dollar',
    amount: '+3.70 USD',
    details: cashbackPackDetailRows(
      'Credited on',
      'Jan 13, 2026, 16:06 UTC',
      'Jan 12',
      '#12345678',
    ),
    orders: [
      {
        id: 'cb-j12-1',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 9088801'],
        date: '13 Jan',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: CASHBACK_LEG_CHIP,
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: cashbackOrderDetailRows('Jan 12', '9088801', 'Jan 12, 2026, 16:06 UTC'),
        },
      },
      {
        id: 'cb-j12-2',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 9088802'],
        date: '13 Jan',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: CASHBACK_LEG_CHIP,
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: cashbackOrderDetailRows('Jan 12', '9088802', 'Jan 12, 2026, 16:06 UTC'),
        },
      },
      {
        id: 'cb-j12-3',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 9088803'],
        date: '13 Jan',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: CASHBACK_LEG_CHIP,
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: cashbackOrderDetailRows('Jan 12', '9088803', 'Jan 12, 2026, 16:06 UTC'),
        },
      },
    ],
  },
}
