import type { PackConfig, PackVariantKey } from './types'

export const PACK_CONFIG: Record<PackVariantKey, PackConfig> = {
  'loyalty-upcoming': {
    navTitle: 'Loyalty rewards',
    chip: { text: 'Upcoming', tone: 'warning' },
    heroIcon: 'crown',
    amount: '+45.78 EXD',
    details: [
      { label: 'Become available on', value: '31 Jan 2026, 18:43' },
      { label: 'For period', value: '21 Jan 2026 – 25 Jan 2026' },
    ],
    orders: [
      {
        id: 'ly-u-1',
        listIcon: 'crown',
        title: 'Loyalty reward',
        amount: '+15.27 EXD',
        meta: ['Account: #12345678', 'Order: 8829103'],
        date: 'Jan 25, 16:06',
        detail: {
          navTitle: 'Loyalty reward',
          chip: { text: 'Upcoming', tone: 'warning' },
          heroIcon: 'crown',
          amount: '+15.27 EXD',
          details: [
            { label: 'Pack', value: 'Loyalty rewards · Jan 21–25' },
            { label: 'Account', value: '#12345678' },
            { label: 'Order', value: '8829103' },
            { label: 'Trading volume', value: '12.4 lots (period)' },
            { label: 'Tier applied', value: 'Ultimate · x2' },
            { label: 'Accrued on', value: '25 Jan 2026, 16:06' },
            { label: 'Line ref.', value: 'LY-ORD-8829103' },
          ],
        },
      },
      {
        id: 'ly-u-2',
        listIcon: 'crown',
        title: 'Loyalty reward',
        amount: '+15.26 EXD',
        meta: ['Account: #12345678', 'Order: 8829104'],
        date: 'Jan 25, 16:06',
        detail: {
          navTitle: 'Loyalty reward',
          chip: { text: 'Upcoming', tone: 'warning' },
          heroIcon: 'crown',
          amount: '+15.26 EXD',
          details: [
            { label: 'Pack', value: 'Loyalty rewards · Jan 21–25' },
            { label: 'Account', value: '#12345678' },
            { label: 'Order', value: '8829104' },
            { label: 'Trading volume', value: '11.9 lots (period)' },
            { label: 'Tier applied', value: 'Ultimate · x2' },
            { label: 'Accrued on', value: '25 Jan 2026, 16:06' },
            { label: 'Line ref.', value: 'LY-ORD-8829104' },
          ],
        },
      },
      {
        id: 'ly-u-3',
        listIcon: 'crown',
        title: 'Loyalty reward',
        amount: '+15.25 EXD',
        meta: ['Account: #12345678', 'Order: 8829105'],
        date: 'Jan 25, 16:06',
        detail: {
          navTitle: 'Loyalty reward',
          chip: { text: 'Upcoming', tone: 'warning' },
          heroIcon: 'crown',
          amount: '+15.25 EXD',
          details: [
            { label: 'Pack', value: 'Loyalty rewards · Jan 21–25' },
            { label: 'Account', value: '#12345678' },
            { label: 'Order', value: '8829105' },
            { label: 'Trading volume', value: '11.8 lots (period)' },
            { label: 'Tier applied', value: 'Ultimate · x2' },
            { label: 'Accrued on', value: '25 Jan 2026, 16:06' },
            { label: 'Line ref.', value: 'LY-ORD-8829105' },
          ],
        },
      },
    ],
  },
  'loyalty-activated': {
    navTitle: 'Loyalty rewards',
    chip: { text: 'Activated', tone: 'success' },
    heroIcon: 'crown',
    amount: '+89.23 EXD',
    details: [
      { label: 'Moved to available on', value: '15 Jan 2026, 16:15' },
      { label: 'For trading period', value: '5–10 Jan 2026' },
    ],
    orders: [
      {
        id: 'ly-a-1',
        listIcon: 'crown',
        title: 'Loyalty reward',
        amount: '+44.62 EXD',
        meta: ['Account: #12345678', 'Order: 8812001'],
        date: '10 Jan 2026',
        detail: {
          navTitle: 'Loyalty reward',
          chip: { text: 'Activated', tone: 'success' },
          heroIcon: 'crown',
          amount: '+44.62 EXD',
          details: [
            { label: 'Pack', value: 'Loyalty rewards · Jan 5–10' },
            { label: 'Credited to', value: 'Available rewards' },
            { label: 'Account', value: '#12345678' },
            { label: 'Order', value: '8812001' },
            { label: 'Trading volume', value: '28.1 lots (period)' },
            { label: 'Posted on', value: '15 Jan 2026, 16:15' },
            { label: 'Line ref.', value: 'LY-ORD-8812001' },
          ],
        },
      },
      {
        id: 'ly-a-2',
        listIcon: 'crown',
        title: 'Loyalty reward',
        amount: '+44.61 EXD',
        meta: ['Account: #12345678', 'Order: 8812002'],
        date: '10 Jan 2026',
        detail: {
          navTitle: 'Loyalty reward',
          chip: { text: 'Activated', tone: 'success' },
          heroIcon: 'crown',
          amount: '+44.61 EXD',
          details: [
            { label: 'Pack', value: 'Loyalty rewards · Jan 5–10' },
            { label: 'Credited to', value: 'Available rewards' },
            { label: 'Account', value: '#12345678' },
            { label: 'Order', value: '8812002' },
            { label: 'Trading volume', value: '27.9 lots (period)' },
            { label: 'Posted on', value: '15 Jan 2026, 16:15' },
            { label: 'Line ref.', value: 'LY-ORD-8812002' },
          ],
        },
      },
    ],
  },
  'cashback-upcoming': {
    navTitle: 'Cashback',
    chip: { text: 'Upcoming', tone: 'warning' },
    heroIcon: 'dollar',
    amount: '+3.70 USD',
    details: [
      { label: 'Will be credited on', value: 'Tomorrow' },
      { label: 'For', value: 'Daily trading' },
    ],
    orders: [
      {
        id: 'cb-u-1',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 12345682'],
        date: 'Jan 15, 16:06',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: { text: 'Upcoming', tone: 'warning' },
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: [
            { label: 'Pack', value: 'Cashback · daily session' },
            { label: 'Account', value: '#12345678' },
            { label: 'Order', value: '12345682' },
            { label: 'EXD debited', value: '1.04 EXD' },
            { label: 'USD leg (est.)', value: '+1.23 USD' },
            { label: 'Rate', value: '1 EXD = 1.185 USD' },
            { label: 'Conversion ref.', value: 'CB-CONV-1001' },
          ],
        },
      },
      {
        id: 'cb-u-2',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 12345683'],
        date: 'Jan 15, 16:06',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: { text: 'Upcoming', tone: 'warning' },
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: [
            { label: 'Pack', value: 'Cashback · daily session' },
            { label: 'Account', value: '#12345678' },
            { label: 'Order', value: '12345683' },
            { label: 'EXD debited', value: '1.04 EXD' },
            { label: 'USD leg (est.)', value: '+1.23 USD' },
            { label: 'Rate', value: '1 EXD = 1.185 USD' },
            { label: 'Conversion ref.', value: 'CB-CONV-1002' },
          ],
        },
      },
      {
        id: 'cb-u-3',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 12345684'],
        date: 'Jan 15, 16:06',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: { text: 'Upcoming', tone: 'warning' },
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: [
            { label: 'Pack', value: 'Cashback · daily session' },
            { label: 'Account', value: '#12345678' },
            { label: 'Order', value: '12345684' },
            { label: 'EXD debited', value: '1.04 EXD' },
            { label: 'USD leg (est.)', value: '+1.24 USD' },
            { label: 'Rate', value: '1 EXD = 1.185 USD' },
            { label: 'Conversion ref.', value: 'CB-CONV-1003' },
          ],
        },
      },
    ],
  },
  'cashback-activated': {
    navTitle: 'Cashback',
    chip: { text: 'Credited', tone: 'success' },
    heroIcon: 'dollar',
    amount: '+3.70 USD',
    details: [
      { label: 'Credited on', value: '14 Jan 2026, 16:06' },
      { label: 'For trading on', value: '13 Jan 2026' },
      { label: 'Account', value: '#12345678' },
    ],
    orders: [
      {
        id: 'cb-a-1',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 9130201'],
        date: '14 Jan 2026',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: { text: 'Credited', tone: 'success' },
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: [
            { label: 'Pack', value: 'Cashback · 13 Jan 2026' },
            { label: 'Credited as', value: '+1.23 USD (batch)' },
            { label: 'Account', value: '#12345678' },
            { label: 'Order', value: '9130201' },
            { label: 'EXD debited', value: '1.04 EXD' },
            { label: 'Settled on', value: '14 Jan 2026, 16:06' },
            { label: 'Transaction ID', value: 'CB-91302-EX' },
          ],
        },
      },
      {
        id: 'cb-a-2',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 9130202'],
        date: '14 Jan 2026',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: { text: 'Credited', tone: 'success' },
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: [
            { label: 'Pack', value: 'Cashback · 13 Jan 2026' },
            { label: 'Credited as', value: '+1.23 USD (batch)' },
            { label: 'Account', value: '#12345678' },
            { label: 'Order', value: '9130202' },
            { label: 'EXD debited', value: '1.04 EXD' },
            { label: 'Settled on', value: '14 Jan 2026, 16:06' },
            { label: 'Transaction ID', value: 'CB-91302-EX' },
          ],
        },
      },
      {
        id: 'cb-a-3',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 9130203'],
        date: '14 Jan 2026',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: { text: 'Credited', tone: 'success' },
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: [
            { label: 'Pack', value: 'Cashback · 13 Jan 2026' },
            { label: 'Credited as', value: '+1.24 USD (batch)' },
            { label: 'Account', value: '#12345678' },
            { label: 'Order', value: '9130203' },
            { label: 'EXD debited', value: '1.04 EXD' },
            { label: 'Settled on', value: '14 Jan 2026, 16:06' },
            { label: 'Transaction ID', value: 'CB-91302-EX' },
          ],
        },
      },
    ],
  },
  'cashback-activated-jan12': {
    navTitle: 'Cashback',
    chip: { text: 'Credited', tone: 'success' },
    heroIcon: 'dollar',
    amount: '+3.70 USD',
    details: [
      { label: 'Credited on', value: '13 Jan 2026, 16:06' },
      { label: 'For trading on', value: '12 Jan 2026' },
      { label: 'Account', value: '#12345678' },
    ],
    orders: [
      {
        id: 'cb-j12-1',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 9088801'],
        date: '13 Jan 2026',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: { text: 'Credited', tone: 'success' },
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: [
            { label: 'Pack', value: 'Cashback · 12 Jan 2026' },
            { label: 'Credited as', value: '+1.23 USD (batch)' },
            { label: 'Account', value: '#12345678' },
            { label: 'Order', value: '9088801' },
            { label: 'EXD debited', value: '1.04 EXD' },
            { label: 'Settled on', value: '13 Jan 2026, 16:06' },
            { label: 'Transaction ID', value: 'CB-90888-EX' },
          ],
        },
      },
      {
        id: 'cb-j12-2',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 9088802'],
        date: '13 Jan 2026',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: { text: 'Credited', tone: 'success' },
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: [
            { label: 'Pack', value: 'Cashback · 12 Jan 2026' },
            { label: 'Credited as', value: '+1.23 USD (batch)' },
            { label: 'Account', value: '#12345678' },
            { label: 'Order', value: '9088802' },
            { label: 'EXD debited', value: '1.04 EXD' },
            { label: 'Settled on', value: '13 Jan 2026, 16:06' },
            { label: 'Transaction ID', value: 'CB-90888-EX' },
          ],
        },
      },
      {
        id: 'cb-j12-3',
        listIcon: 'exchange',
        title: 'EXD → Cashback',
        amount: '-1.04 EXD',
        amountClass: 'negative',
        meta: ['Account: #12345678', 'Order: 9088803'],
        date: '13 Jan 2026',
        detail: {
          navTitle: 'EXD → Cashback',
          chip: { text: 'Credited', tone: 'success' },
          heroIcon: 'dollar',
          amount: '-1.04 EXD',
          amountTone: 'negative',
          details: [
            { label: 'Pack', value: 'Cashback · 12 Jan 2026' },
            { label: 'Credited as', value: '+1.24 USD (batch)' },
            { label: 'Account', value: '#12345678' },
            { label: 'Order', value: '9088803' },
            { label: 'EXD debited', value: '1.04 EXD' },
            { label: 'Settled on', value: '13 Jan 2026, 16:06' },
            { label: 'Transaction ID', value: 'CB-90888-EX' },
          ],
        },
      },
    ],
  },
}
